// advanced/d3-react/src/components/StreamGraph.js
import React, { Component } from "react";
import "../App.css";
import {
  stack,
  area,
  curveBasis,
  stackOrderInsideOut,
  stackOffsetSilhouette,
} from "d3-shape";
import { range } from "d3-array";
import { scaleLinear } from "d3-scale";

function StreamGraph({ data, size, colorScale }) {
  const stackData = range(30).map(() => ({}));
  for (let x = 0; x < 30; x++) {
    data.forEach((country) => {
      stackData[x][country.id] = country.data[x];
    });
  }
  const xScale = scaleLinear().domain([0, 30]).range([0, size[0]]);
  const yScale = scaleLinear().domain([0, 60]).range([size[1], 0]);

  const stackLayout = stack()
    .offset(stackOffsetSilhouette)
    .order(stackOrderInsideOut)
    .keys(Object.keys(stackData[0]));
  const stackArea = area()
    .x((d, i) => xScale(i))
    .y0((d) => yScale(d[0]))
    .y1((d) => yScale(d[1]))
    .curve(curveBasis);

  const stacks = stackLayout(stackData).map((d, i) => (
    <path
      key={"stack" + i}
      d={stackArea(d)}
      style={{
        fill: colorScale(data[i].launchday),
        stroke: "black",
        strokeOpacity: 0.25,
      }}
    ></path>
  ));
  return (
    <svg width={size[0]} height={size[1]}>
      <g transform={`translate(0,${-size[1] / 2})`}>{stacks}</g>
    </svg>
  );
}

export default StreamGraph;

// fundamentals/layout/src/components/streamgraph.vue
<script setup>
import * as d3 from "d3";
import { onMounted, ref } from "vue";

const dataColumn = ref([]);
const dataset = ref([]);

const xScale = d3.scaleLinear().domain([0, 10]).range([0, 500]);
const yScale = d3.scaleLinear().domain([0, 100]).range([500, 0]);
const movies = [
  "titanic",
  "avatar",
  "akira",
  "frozen",
  "deliverance",
  "avengers",
];

var fillScale = d3
  .scaleOrdinal()
  .domain(movies)
  .range(["#fcd88a", "#cf7c1c", "#93c464", "#75734F", "#5eafc6", "#41a368"]);

const stackLayout = d3.stack().keys(movies);
const stackArea = d3
  .area()
  .x((d, i) => xScale(i))
  .y0((d) => yScale(d[0])) // 这里的d[0]是和 stackLayout 处理过的数据对应的
  .y1((d) => yScale(d[1]));

onMounted(() => {
  d3.csv("/movies.csv").then((data) => {
    dataColumn.value = data.columns.filter((item) => item !== "day");

    dataset.value = data.map((item) => {
      Object.keys(item).forEach((key) => {
        item[key] = Number(item[key]);
      });
      return item;
    });

    console.log(stackLayout(dataset.value));

    // d3.select("svg")
    //   .selectAll("path")
    //   .data(stackLayout(dataset.value))
    //   .enter()
    //   .append("path")
    //   .attr("d", stackArea)
    //   .style("fill", (d, i) => fillScale(i));

    stackLayout.offset(d3.stackOffsetSilhouette).order(d3.stackOrderInsideOut);
    stackArea.curve(d3.curveBasis);
    yScale.domain([-50, 50]);

    d3.select("svg")
      .selectAll("path")
      .data(stackLayout(dataset.value))
      .enter()
      .append("path")
      .attr("d", stackArea)
      .style("fill", (d, i) => fillScale(i));
  });
});
</script>

<template>
  <svg id="svg" width="500px" height="500px"></svg>
</template>

<style scoped></style>
